# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory
WORKDIR /app

# Install dependencies
RUN pip install requests

# Copy the current directory contents into the container at /app
COPY . /app

# Run the script
CMD ["python", "client.py"]
